
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <math.h>
#include "calculadora.h"

double *
sumar_1_svc(datos arg1,  struct svc_req *rqstp)
{
	static double  result;

	result = arg1.operador1 + arg1.operador2;

	return &result;
}

double *
restar_1_svc(datos arg1,  struct svc_req *rqstp)
{
	static double  result;

	result = arg1.operador1 - arg1.operador2;

	return &result;
}

double *
multiplicar_1_svc(datos arg1,  struct svc_req *rqstp)
{
	static double  result;

	result = arg1.operador1 * arg1.operador2;

	return &result;
}

double *
dividir_1_svc(datos arg1,  struct svc_req *rqstp)
{
	static double  result;

	result = arg1.operador1 / arg1.operador2;

	return &result;
}

double *
potencia_1_svc(datos arg1,  struct svc_req *rqstp)
{
	static double  result;

	result = pow(arg1.operador1,arg1.operador2);

	return &result;
}

datos *
sumarvector_1_svc(datos arg1,  struct svc_req *rqstp)
{
	static datos  result;

	result.operador1 = arg1.operador3 + arg1.operador1;
	result.operador2 = arg1.operador4 + arg1.operador2;

	return &result;
}

datos *
restarvector_1_svc(datos arg1,  struct svc_req *rqstp)
{
	static datos  result;

	result.operador1 = arg1.operador3 - arg1.operador1;
	result.operador2 = arg1.operador4 - arg1.operador2;

	return &result;
}

double *
multiplicarvector_1_svc(datos arg1,  struct svc_req *rqstp)
{
	static double  result;
	double resultadox;
	double resultadoy;

	resultadox = arg1.operador3 - arg1.operador1;
	resultadoy = arg1.operador4 - arg1.operador2;

	result = resultadox + resultadoy;

	return &result;
}
