

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdlib.h>


void
calculadora_1(char *host, datos data, char operacion)
{
	CLIENT *clnt;
	double  *resultadoSimple;
	datos  *resultadoCompuesto;
	

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORAV0, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(operacion) {
		case '+':

		printf("Entra en operacion suma \n");
			if(data.operador3==0 && data.operador4==0){
				resultadoSimple = sumar_1(data, clnt);
				printf("%lf \n", *resultadoSimple);
			}

			else {
				resultadoCompuesto = sumarvector_1(data, clnt);
				printf("%lf x %lf y  \n", (*resultadoCompuesto).operador1,(*resultadoCompuesto).operador2 );
			}
			
		break;

		case '-':
			if(data.operador3==0 && data.operador4==0){
				resultadoSimple = restar_1(data, clnt);
				printf("%lf \n", *resultadoSimple);
			}

			else {
				resultadoCompuesto = restarvector_1(data, clnt);
				printf("%lf x %lf y  \n", (*resultadoCompuesto).operador1,(*resultadoCompuesto).operador2 );
			}
		break;

		case '*':
			if(data.operador3==0 && data.operador4==0){
				resultadoSimple = multiplicar_1(data, clnt);
				printf("%lf \n", *resultadoSimple);
			}

			else {
				resultadoSimple = multiplicarvector_1(data, clnt);
				printf("%lf x %lf y  \n", (*resultadoCompuesto).operador1,(*resultadoCompuesto).operador2 );
			}
		break;

		case '/':
			resultadoSimple = dividir_1(data, clnt);
			printf("%lf \n", *resultadoSimple);
		break;

		case '^':
			resultadoSimple = potencia_1(data, clnt);
			printf("%lf \n", *resultadoSimple);
		break;

		default:
		printf("No se ha asignado ninguna opcion \n");

		break;

	};
	

	
	if ((resultadoSimple == (double *) NULL) && ((resultadoCompuesto == (datos *) NULL))) {
				clnt_perror (clnt, "call failed\n");
	}

	




#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	char operacion;
	datos data;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];	


	switch(argc) {
		case 5:
			printf("Entra en 2 digitos \n");
			data.operador1=atof(argv[2]);
			data.operador2=atof(argv[4]);
			operacion = (char) argv[3][0];
	
			data.operador3=0;
			data.operador4=0;
		break;

		case 7:
		printf("Entra en 4 digitos \n");

			data.operador1 = atof(argv[2]);
			data.operador2 = atof(argv[3]);
			data.operador3 = atof(argv[5]);
			data.operador4 = atof(argv[6]);
			operacion = (char)argv[4][0];
		    printf("valores  %lf %lf x, %lf %lf \n", atof(argv[2]), atof(argv[3]), atof(argv[5]), atof(argv[6]));
		    printf("opcion  %c \n", operacion);

		break;

		default:
		printf("No se ha asignado ninguna opcion %d \n", argc);

		break;

		
	};

	

	calculadora_1 (host, data, operacion);
	exit (0);
}

