/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct datos {
	double operador1;
	double operador2;
	double operador3;
	double operador4;
};
typedef struct datos datos;

#define CALCULADORA 0x20000001
#define CALCULADORAV0 1

#if defined(__STDC__) || defined(__cplusplus)
#define sumar 1
extern  double * sumar_1(datos , CLIENT *);
extern  double * sumar_1_svc(datos , struct svc_req *);
#define restar 2
extern  double * restar_1(datos , CLIENT *);
extern  double * restar_1_svc(datos , struct svc_req *);
#define multiplicar 3
extern  double * multiplicar_1(datos , CLIENT *);
extern  double * multiplicar_1_svc(datos , struct svc_req *);
#define dividir 4
extern  double * dividir_1(datos , CLIENT *);
extern  double * dividir_1_svc(datos , struct svc_req *);
#define potencia 5
extern  double * potencia_1(datos , CLIENT *);
extern  double * potencia_1_svc(datos , struct svc_req *);
#define sumarVector 7
extern  datos * sumarvector_1(datos , CLIENT *);
extern  datos * sumarvector_1_svc(datos , struct svc_req *);
#define restarVector 8
extern  datos * restarvector_1(datos , CLIENT *);
extern  datos * restarvector_1_svc(datos , struct svc_req *);
#define multiplicarVector 9
extern  double * multiplicarvector_1(datos , CLIENT *);
extern  double * multiplicarvector_1_svc(datos , struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sumar 1
extern  double * sumar_1();
extern  double * sumar_1_svc();
#define restar 2
extern  double * restar_1();
extern  double * restar_1_svc();
#define multiplicar 3
extern  double * multiplicar_1();
extern  double * multiplicar_1_svc();
#define dividir 4
extern  double * dividir_1();
extern  double * dividir_1_svc();
#define potencia 5
extern  double * potencia_1();
extern  double * potencia_1_svc();
#define sumarVector 7
extern  datos * sumarvector_1();
extern  datos * sumarvector_1_svc();
#define restarVector 8
extern  datos * restarvector_1();
extern  datos * restarvector_1_svc();
#define multiplicarVector 9
extern  double * multiplicarvector_1();
extern  double * multiplicarvector_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datos (XDR *, datos*);

#else /* K&R C */
extern bool_t xdr_datos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
