/*CLIENT
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdlib.h>


void
calculadora_1(char *host, double valor1, char operacion, double valor2)
{
	CLIENT *clnt;
	double  *resultado;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORAV0, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(operacion) {
		case '+':
			resultado = sumar_1(valor1, valor2, clnt);
		break;

		case '-':
			resultado = restar_1(valor1, valor2, clnt);
			//printf("%s\n", *resultado);
		break;

		case '*':
			resultado = multiplicar_1(valor1, valor2, clnt);
			//printf("%s\n", *resultado);
		break;

		case '/':
			resultado = dividir_1(valor1, valor2, clnt);
			//printf("%s\n", *resultado);
		break;

	};

	printf("%lf \n", *resultado);
	if (resultado == (double *) NULL) {
				clnt_perror (clnt, "call failed");
	}


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	double valor1;
	double valor2;
	char operacion;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];	
	valor1= atof(argv[2]);
	operacion = (char)argv[3][0];
	valor2 = atof(argv[4]);

	//printf("He leido como operacion: %s", operacion );
	

	calculadora_1 (host, valor1, operacion ,valor2);
exit (0);
}
