/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"
#include <dirent.h>

reddir_res *
readdir_1_svc(nametype dirnamerg1,  struct svc_req *rqstp)
{
	static reddir_res  result;
	DIR *dirp;
	struct dirent *d;
	namelist nl;
	namelist *nlp;
	

	static readdir_res result;

	dirp = opendir(dirname);

	return &result;
}
