/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_datos (XDR *xdrs, datos *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->operador1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->operador2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->operador3))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->operador4))
		 return FALSE;
	return TRUE;
}
